#!/usr/bin/env zsh

REALNAME=$(~/bin/portable-getent passwd $USER|awk -F : '{print $5}' | awk -F , '{print $1}')
DATE=$(date)
YEAR=$(date +%Y)
FILENAME=$(echo $1 | sed 's/[^/]*\///')
FILE=$(echo $FILENAME | sed 's/\..*//')
FILEBIG=$(echo $FILE | tr '[:lower:]' '[:upper:]')
sed	"s/%%AUTHOR%%/$REALNAME/g;
	s/%%DATE%%/$DATE/g;
	s/%%YEAR%%/$YEAR/g;
	s/%%FILENAME%%/$FILENAME/g;
	s/%%FILE%%/$FILE/g;
	s/%%FILEBIG%%/$FILEBIG/g;"
