#!/bin/zsh

MAIL_TO=""

case "$1" in
	commit)
		case "$ARCH_CATEGORY" in
			configurations)
				case "$ARCH_BRANCH" in
					mainline)
						RELEASETYPE="stable"
						MAIL_TO="dreamind@dreamind.de, loeffler@ls-itc.de"
						;;
					devel)
						RELEASETYPE="unstable"
						MAIL_TO=dreamind@dreamind.de
						;;
					*)
						;;
				esac
				;;
		esac
		;;
esac

if [ "$MAIL_TO" ]; then
	( echo "set the_address to \"$MAIL_TO\""
	echo "set the_subject to \"$ARCH_CATEGORY--$ARCH_BRANCH updated\""
	echo -n "set the_body to {\"Hello folks,\", \"\", \"the $RELEASETYPE version of $ARCH_CATEGORY has been updated.\", \"Please update your arch repository.\", \"\", \"\", \"---log-entry---\""
	tla cat-archive-log $ARCH_ARCHIVE/$ARCH_REVISION | while read line; do echo -n ", \"$line\"";done;echo ", \"---log-entry---\"}"
	echo 'tell application "Mail"'
	echo 'set new_message to make new outgoing message with properties {subject:the_subject}'
	echo "set local_sig_list to every signature whose name is \"Normal\""
	echo "repeat with local_sig in local_sig_list"
	echo "end repeat"
	echo "tell new_message"
	echo "set local_sig to content"
	echo "set content to \"\""
	echo "repeat with body_part in the_body"
	echo 'set content to content & body_part & return'
	echo "end repeat"
	echo 'set content to content & local_sig'
	echo 'make new to recipient at end of to recipients with properties {address:the_address}'
	echo "set message signature to local_sig"
	echo 'end tell'
	echo 'send new_message'
	echo 'end tell' ) | osascript
fi

