#!/bin/zsh

if [ "$TERM" != "dumb" ] && which dircolors > /dev/null; then
	eval `dircolors -b`
	if which gls >/dev/null; then
		alias ls='gls --color=auto'
		alias ll='gls -l --color=auto'
		alias la='gls -la --color=auto'
	else
		alias ls='ls --color=auto'
		alias ll='ls -l --color=auto'
		alias la='ls -la --color=auto'
	fi
fi

alias grep="grep --color=auto"
alias psgrep="ps xa | grep --color=auto"
alias sudo="sudo -H"
alias kernel_finger="wget -qO- http://www.kernel.org/kdist/finger_banner"
