#!/bin/zsh
# Setup a nicer terminal title
case $TERM in
	xterm*|Eterm|rxvt)
		echo -ne "\033]0;${USER}@${HOST}";\
		if [ ! -z "$UNAME_XTERM_STRING" ]; then
			echo -ne ' :: '${PWD}' :: ['${UNAME_XTERM_STRING}']\007'
		else
			echo -ne ' :: '${PWD}' :: ['$(uname -r)']\007'
		fi
		;;
	*)
		;;
esac

