#!/bin/zsh
fpath=(~/.zsh/functions/completion $fpath)
autoload -U ~/.zsh/functions/completion/*(:t)
autoload -U compinit
autoload -U colors

if [ "$OS" = "Windows_NT" ]; then
	compinit -u
else
	compinit
fi

colors
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''

#zstyle ':completion:*:scp:*' tag-order \
#        'hosts:-host hosts:-domain:domain hosts:-ipaddr:IP\ address *'
zstyle ':completion:*:scp:*' group-order \
        users files all-files hosts-domain hosts-host hosts-ipaddr
#zstyle ':completion:*:ssh:*' tag-order \
#        users 'hosts:-host hosts:-domain:domain hosts:-ipaddr:IP\ address *'
#zstyle ':completion:*:ssh:*' group-order \
#        hosts-domain hosts-host users hosts-ipaddr

zstyle ':completion:*:(ssh|scp):*:hosts-host' ignored-patterns \
        '*.*' loopback localhost
zstyle ':completion:*:(ssh|scp):*:hosts-domain' ignored-patterns \
        '<->.<->.<->.<->' '^*.*' '*@*'
zstyle ':completion:*:(ssh|scp):*:hosts-ipaddr' ignored-patterns \
        '^<->.<->.<->.<->' '127.0.0.<->'
#zstyle ':completion:*:(ssh|scp):*:users' ignored-patterns \
#        adm bin daemon halt lp named shutdown sync
zstyle -e ':completion:*:(ssh|scp|rsync|ping|mtr|traceroute):*' hosts 'reply=(
        ${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) \
                        /dev/null)"}%%[# ]*}//,/ }
        )'

#        ${=${(f)"$(cat /etc/hosts(|)(N) <<(ypcat hosts 2>/dev/null))"}%%\#*}
#zstyle ':completion:*:(ssh|scp):*:my-accounts' users-hosts \
#        my.secret.account@student.uu.se

zstyle ':completion::complete:git(|-help):*' commands all
zstyle ':completion::complete:git:*' verbose false

#source /etc/environment
