#!/bin/zsh
# Fink (Mac OS X) specific stuff

local prefix

if [ $(uname -s) = "Darwin" ]; then
	for prefix in /sw /opt/DarwinPorts /opt/local; do
		if [ -d $prefix ];then
			break
		fi
	done
fi

if [ "$prefix" ]; then

	# manpath
	if [ -z "$MANPATH" ]; then
		MANPATH=`/usr/bin/manpath -q`
	fi
	export MANPATH
	typeset -U manpath
	manpath=($prefix/share/man $manpath)

	# infopath
	export INFOPATH
	typeset -U infopath
	typeset -T INFOPATH infopath
	infopath=($prefix/share/info $prefix/info /usr/share/info)

	# update the java classpath
	if [ -r cat $prefix/share/java/classpath ]; then
		export CLASSPATH
		typeset -U classpath
		typeset -T CLASSPATH classpath
		classpath=(`cat $prefix/share/java/classpath` $classpath)
	fi

	# update the perl searchpath
	export PERL5LIB
	typeset -U perl5lib
	typeset -T PERL5LIB perl5lib
	perl5lib=($prefix/lib/perl5 $prefix/lib/perl5/darwin $prefix/lib/perl5/vendor_perl $perl5lib)

	# setup the DISPLAY variable, so X11 stuff works in the Apple Terminal too.
	if ps xa | grep -v grep | grep -q X11; then
		export DISPLAY=:0
	fi

fi
