#!/bin/zsh
which ssh  >/dev/null && export RSYNC_RSH=ssh
which ssh  >/dev/null && export CVS_RSH=ssh
which vim  >/dev/null && export EDITOR=vim
which less >/dev/null && export PAGER=less
if [ $(uname -s) = "Darwin" ]; then
	export GQSTATE=""
fi

# fix $USER on Solaris
if [ -z "$USER" ] && [ ! -z "$USERNAME" ]; then
	export USER=$USERNAME
fi
