#!/bin/zsh
#export GIT_AUTHOR_NAME="J. Random Hacker"
#export GIT_AUTHOR_EMAIL="nobody@example.org"
#export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
#export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

# If the variables above are set, you may just
# delete the following code...

git() {
	local realname
	local email
	local ok

	# if one of the git environment variables is set,
	# execute git and return...
	if ! test -z "${GIT_AUTHOR_NAME}${GIT_AUTHOR_EMAIL}${GIT_COMMITTER_NAME}${GIT_COMMITTER_EMAIL}"
	then
		command git $*
		return
	fi

	echo "The Git-Environment is not set, please enter" >&2
	echo "Your name and email address below." >&2
	echo >&2

	read realname\?"What is your name? "
	read email\?"What is your email address? "
	echo >&2

	read -q ok\?"Is \"$realname <$email>\" correct? [y/N] "
	echo >&2

	if test $ok = "y"
	then
		echo "Ok, exporting the new Environment and starting git." >&2
		echo >&2
		export GIT_AUTHOR_NAME=$realname
		export GIT_AUTHOR_EMAIL=$email
		export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
		export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL

		command git $*
		return
	fi
}
