#!/bin/zsh

if [ "$TERM" != "dumb" ] && which dircolors > /dev/null; then
	eval `dircolors -b`
	if which gls >/dev/null; then
		alias ls='gls --color=auto'
	else
		alias ls='ls --color=auto'
	fi
fi

alias psgrep="ps xa | grep"
alias sudo="sudo -H"
