#!/bin/zsh

if [ $(uname -s) = Linux -o $(uname -s) = Darwin ]; then
	UNAME_XTERM_STRING=$(uname -r)
elif [ ! -z $OS ]; then
	UNAME_XTERM_STRING=$OS
else
	UNAME_XTERM_STRING="$(uname -s) $(uname -r)"
fi
